CREATE TABLE "caicara-stock_order" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "caicara-stock_order_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"orderDate" date NOT NULL,
	"totalPrice" numeric(10, 2) NOT NULL,
	"status" varchar(32) DEFAULT 'pending' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "caicara-stock_order_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "caicara-stock_order_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"orderId" integer NOT NULL,
	"productId" integer NOT NULL,
	"quantity" integer NOT NULL,
	"price" numeric(10, 2) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "caicara-stock_product" ALTER COLUMN "name" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "caicara-stock_product" ADD COLUMN "description" varchar(256);--> statement-breakpoint
ALTER TABLE "caicara-stock_product" ADD COLUMN "price" numeric(10, 2) NOT NULL;--> statement-breakpoint
ALTER TABLE "caicara-stock_product" ADD COLUMN "quantity" integer NOT NULL;--> statement-breakpoint
ALTER TABLE "caicara-stock_order_item" ADD CONSTRAINT "caicara-stock_order_item_orderId_caicara-stock_order_id_fk" FOREIGN KEY ("orderId") REFERENCES "public"."caicara-stock_order"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "caicara-stock_order_item" ADD CONSTRAINT "caicara-stock_order_item_productId_caicara-stock_product_id_fk" FOREIGN KEY ("productId") REFERENCES "public"."caicara-stock_product"("id") ON DELETE no action ON UPDATE no action;